insert into produtos(codigo, descricao, preco_venda) values(1, 'Alface', 3.50);
insert into produtos(codigo, descricao, preco_venda) values(2, 'Tomate', 7.50);
insert into produtos(codigo, descricao, preco_venda) values(3, 'Batata', 8.50);
insert into produtos(codigo, descricao, preco_venda) values(4, 'Batata Doce', 9.00);
insert into produtos(codigo, descricao, preco_venda) values(5, 'Nikito', 10.00);
insert into produtos(codigo, descricao, preco_venda) values(6, 'Bono', 5.50);
insert into produtos(codigo, descricao, preco_venda) values(7, 'Coca Cola 350 ml lata', 2.50);
insert into produtos(codigo, descricao, preco_venda) values(8, 'Repolho', 1.50);
insert into produtos(codigo, descricao, preco_venda) values(9, 'Limaão', 3.00);
insert into produtos(codigo, descricao, preco_venda) values(10, 'Melão', 3.60);
insert into produtos(codigo, descricao, preco_venda) values(11, 'Melancia', 3.70);
insert into produtos(codigo, descricao, preco_venda) values(12, 'Couve Flor', 4.80);
insert into produtos(codigo, descricao, preco_venda) values(13, 'Aliche', 2.75);
insert into produtos(codigo, descricao, preco_venda) values(14, 'Pera', 1.00);
insert into produtos(codigo, descricao, preco_venda) values(15, 'Biscoito', 8.00);
insert into produtos(codigo, descricao, preco_venda) values(16, 'Papel Higienico Nobre', 13.00);
insert into produtos(codigo, descricao, preco_venda) values(17, 'Manga', 13.50);
insert into produtos(codigo, descricao, preco_venda) values(18, 'Banana', 23.50);
insert into produtos(codigo, descricao, preco_venda) values(19, 'Agua', 13.50);
insert into produtos(codigo, descricao, preco_venda) values(20, 'Pão', 10.50);
